# Generated by Django 3.0.6 on 2020-05-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey_question',
            name='question_type',
            field=models.CharField(choices=[('T1', 'For groups 1, 2, 4 and 5'), ('T2', 'For groups 2, 4 and 5'), ('T3', 'For group 4'), ('T4', 'For group 5')], default='T1', max_length=2),
        ),
    ]
