# Generated by Django 3.0.6 on 2020-05-07 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200507_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questiion_type',
            new_name='question_type',
        ),
    ]
