# Generated by Django 3.0.6 on 2020-05-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200508_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='allotted_group',
        ),
        migrations.RemoveField(
            model_name='student',
            name='final_group',
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.CharField(choices=[('G1', 'Control group'), ('G2', 'Experimental group without choice'), ('G3', 'Experimental group with choice'), ('G4', 'Group 3 choosing not to create MCQ'), ('G5', 'Group 3 choosing to create MCQ')], default='G3', editable=False, max_length=2),
        ),
    ]
