# Generated by Django 3.0.6 on 2020-05-07 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200507_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=2000)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Student_Question')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
