# Generated by Django 3.0.6 on 2020-05-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200523_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='client_timestamp',
            field=models.CharField(default='', max_length=100),
        ),
    ]
