# Generated by Django 3.0.6 on 2020-05-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200508_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='attempted',
        ),
        migrations.AddField(
            model_name='student',
            name='stage',
            field=models.CharField(choices=[('S1', 'Information page'), ('S2', 'Quiz'), ('S3', 'Results')], default='S1', max_length=2),
        ),
    ]
