# Generated by Django 3.0.6 on 2020-05-08 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200508_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_question',
            name='by_student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator_of', to='polls.Student'),
        ),
    ]
