# Generated by Django 3.0.6 on 2020-05-13 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200509_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=2000)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('question_type', models.CharField(choices=[('T1', 'For groups 1, 2 and 3'), ('T2', 'For groups 2 and 3'), ('T3', 'For groups 3')], default='T1', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.CharField(choices=[('G1', 'Control group'), ('G2', 'Experimental group without choice'), ('G3', 'Experimental group with choice'), ('G4', 'Group 3 choosing not to create MCQ'), ('G5', 'Group 3 choosing to create MCQ')], default='G1', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='stage',
            field=models.CharField(choices=[('S1', 'Quiz'), ('S2', 'Survey'), ('S3', 'Results')], default='S1', max_length=2),
        ),
        migrations.CreateModel(
            name='Survey_Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=2000)),
                ('is_correct', models.BooleanField(default=False)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Survey_Question')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
