# Generated by Django 3.0.6 on 2020-05-13 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20200513_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.CharField(choices=[('G1', 'Control group'), ('G2', 'Experimental group without choice'), ('G3', 'Experimental group with choice'), ('G4', 'Group 3 choosing not to create MCQ'), ('G5', 'Group 3 choosing to create MCQ')], default='G2', max_length=2),
        ),
        migrations.CreateModel(
            name='Student_Survey_Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Student')),
                ('survey_choice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Survey_Choice')),
                ('survey_question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Survey_Question')),
            ],
        ),
    ]
