# Generated by Django 3.0.6 on 2020-05-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20200513_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_survey_response',
            name='survey_choice_id',
        ),
        migrations.AddField(
            model_name='student_survey_response',
            name='survey_choice',
            field=models.CharField(choices=[('C1', 'Strongly disagree'), ('C2', 'Somewhat disagree'), ('C3', 'Neither agree nor disagree'), ('C4', 'Somewhat agree'), ('C5', 'Strongly agree')], default='C1', max_length=2),
        ),
        migrations.DeleteModel(
            name='Survey_Choice',
        ),
    ]
