# Generated by Django 3.0.6 on 2020-05-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20200513_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_survey_response',
            old_name='survey_choice',
            new_name='survey_choice_id',
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.CharField(choices=[('G1', 'Control group'), ('G2', 'Experimental group without choice'), ('G3', 'Experimental group with choice'), ('G4', 'Group 3 choosing not to create MCQ'), ('G5', 'Group 3 choosing to create MCQ')], default='G3', max_length=2),
        ),
    ]
