# Generated by Django 3.0.6 on 2020-05-21 03:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='element_id',
            field=models.CharField(default='def', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='element_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(max_length=100),
        ),
    ]
